// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExitFullscreen() {
  return window['go']['main']['App']['ExitFullscreen']();
}

export function ReadImage(arg1) {
  return window['go']['main']['App']['ReadImage'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}
