// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExitFullscreen():Promise<void>;

export function ReadImage(arg1:string):Promise<string>;

export function SelectDirectory():Promise<Array<string>>;

export function ToggleFullscreen():Promise<void>;
