// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddDirectoryToPlaylist():Promise<main.DirectoryImages>;

export function AddTag(arg1:string,arg2:string):Promise<Array<string>>;

export function ExitFullscreen():Promise<void>;

export function GetAllTags():Promise<Array<string>>;

export function GetTags(arg1:string):Promise<Array<string>>;

export function IsLiked(arg1:string):Promise<boolean>;

export function ReadImage(arg1:string):Promise<string>;

export function SelectDirectory():Promise<Array<string>>;

export function ToggleFullscreen():Promise<void>;

export function ToggleLikeImage(arg1:string):Promise<boolean>;
