// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDirectoryToPlaylist() {
  return window['go']['main']['App']['AddDirectoryToPlaylist']();
}

export function AddTag(arg1, arg2) {
  return window['go']['main']['App']['AddTag'](arg1, arg2);
}

export function ExitFullscreen() {
  return window['go']['main']['App']['ExitFullscreen']();
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetTags(arg1) {
  return window['go']['main']['App']['GetTags'](arg1);
}

export function IsLiked(arg1) {
  return window['go']['main']['App']['IsLiked'](arg1);
}

export function ReadImage(arg1) {
  return window['go']['main']['App']['ReadImage'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}

export function ToggleLikeImage(arg1) {
  return window['go']['main']['App']['ToggleLikeImage'](arg1);
}
